@startuml
'https://plantuml.com/class-diagram

class App{
main()
DoesProductExist()
Printer()
}
class Object{
 Products[] products;
 int I;
}
class Products{
 String name;
 double price;
 int quantity;
}


App <|- Object

App <|- Products
Products <|- App

Products<|- Object

@enduml